version: '3.7'
services:
  db_bookings:
    image: mysql:5.7.31
    container_name: db_bookings
    hostname: db_bookings
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'bookingdb'
      MYSQL_USER: 'booking'
      MYSQL_PASSWORD: 'booking2020++'
    ports:
      - 33060:3306
    volumes:
      - ./src/main/resources/databases:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping https://linuxize.com/post/how-to-remove-docker-images-containers-volumes-and-networks/", "-h", "localhost"]
      timeout: 20s
      retries: 10
  bookings-service:
    image: bookings-service:latest
    container_name: bookings-service
    hostname: bookings-service
    restart: always
    ports:
      - 8090:8090
    networks:
      - backend
    depends_on:
      - db_bookings
    environment:
      - SERVICE_PORTS=8090
      - DATABASE_HOST=db_bookings
      - DATABASE_USER=booking
      - DATABASE_PASSWORD=booking2020++
      - DATABASE_NAME=bookingdb
      - DATABASE_PORT=33060

networks:
  backend:
    external: true
